#  Recordatorio: Producto Interno en Notación de Dirac

El **producto interno** es una operación fundamental en un espacio de Hilbert, que generaliza el **producto punto** de la geometría euclidiana.  

---

##  Definición en notación de Dirac

Dado un par de vectores $\ket{v_i}$ y $\ket{v_j}$, su **producto interno** se escribe como:

$$
\braket{v_i | v_j} = \bra{v_i}\ket{v_j}
$$

- $\ket{v_j}$ → vector columna (ket).  
- $\bra{v_i}$ → conjugado transpuesto de $\ket{v_i}$ (bra).  
- $\braket{v_i | v_j}$ → es un **número complejo**.  

---

##  Propiedades

1. **Linealidad**:  
   $$
   \braket{v_i | a u + b w} = a \braket{v_i | u} + b \braket{v_i | w}
   $$

2. **Conjugación**:  
   $$
   \braket{v_i | v_j} = \braket{v_j | v_i}^*
   $$

3. **Norma inducida**:  
   $$
   \|v_i\|^2 = \braket{v_i | v_i}
   $$

---

##  Caso especial: Ortogonalidad

Si

$$
\braket{v_i | v_j} = 0
$$

entonces $\ket{v_i}$ y $\ket{v_j}$ son **ortogonales**.

**Interpretación geométrica**:  
- Generaliza la idea de **perpendicularidad** en espacios reales.  
- En $\mathbb{R}^n$, coincide con que el ángulo entre $\vec v_i$ y $\vec v_j$ es de $90^\circ$.  

**Interpretación cuántica**:  
- Los estados $\ket{v_i}$ y $\ket{v_j}$ son **mutuamente excluyentes**.  
- Si el sistema está en $\ket{v_i}$, la probabilidad de medirlo en $\ket{v_j}$ es cero.  

---

##  Ejemplo sencillo en $\mathbb{R}^2$

Sea

$$
\ket{v_1} = \begin{bmatrix} 1 \\ 0 \end{bmatrix}, \quad
\ket{v_2} = \begin{bmatrix} 0 \\ 1 \end{bmatrix}
$$

Entonces:

$$
\braket{v_1 | v_2} = \begin{bmatrix} 1 & 0 \end{bmatrix} 
\begin{bmatrix} 0 \\ 1 \end{bmatrix} = 0
$$

> Son vectores **ortogonales**.


#  Recordatorio: Ortogonalidad y Ortonormalidad en un Espacio de Hilbert

En un **espacio de Hilbert**, los conceptos de **ortogonalidad** y **ortonormalidad** generalizan ideas geométricas familiares (como perpendicularidad y vectores unitarios) al ámbito complejo.  

---

##  1. Ortogonalidad

Dos vectores $\ket{u}$ y $\ket{v}$ son **ortogonales** si su producto interno es cero:  

$$
\braket{u | v} = 0
$$

- En términos geométricos: generaliza la **perpendicularidad**.  
- En $\mathbb{R}^n$, esto equivale a que el ángulo entre $\vec{u}$ y $\vec{v}$ es de $90^\circ$.  
- En mecánica cuántica: estados ortogonales representan resultados **mutuamente excluyentes** de una medición.  

---

##  2. Ortonormalidad

Un conjunto de vectores $\{\ket{v_1}, \ket{v_2}, \dots, \ket{v_n}\}$ es **ortonormal** si cumple dos condiciones:  

1. **Ortogonalidad**:  
   $$
   \braket{v_i | v_j} = 0 \quad \text{si } i \neq j
   $$

2. **Normalización**:  
   $$
   \braket{v_i | v_i} = 1 \quad \forall i
   $$

En conjunto:  

$$
\braket{v_i | v_j} = \delta_{ij}
$$

donde $\delta_{ij}$ es el **delta de Kronecker**:  

- $\delta_{ij} = 1$ si $i=j$  
- $\delta_{ij} = 0$ si $i\neq j$  

---

##  3. Interpretación geométrica y cuántica

🔹 **Geométrica**:  
- Vectores ortonormales forman una **base ortonormal** en el espacio vectorial.  
- Equivale a tener vectores unitarios perpendiculares, como los ejes $x$, $y$, $z$ en $\mathbb{R}^3$.  

🔹 **Cuántica**:  
- Una base ortonormal representa un conjunto completo de **resultados posibles de una medición**.  
- La condición $\braket{v_i | v_j} = \delta_{ij}$ garantiza que medir en un estado $\_

# Recordatorio: Matrices Hermíticas en un Espacio de Hilbert

---

##  1. Espacio de Hilbert: el escenario

Un **espacio de Hilbert** es un espacio vectorial complejo con un **producto interno**.  
Este producto interno nos permite:

- **Medir longitudes de vectores:**

$$
\|\ket{\psi}\|^2 = \braket{\psi | \psi}
$$

- **Medir ángulos entre vectores:**

$$
\cos \theta = \frac{\braket{\phi | \psi}}{\|\phi\| \, \|\psi\|}
$$

- **Garantizar convergencia de secuencias de vectores** (es un espacio completo).

> En mecánica cuántica: los estados (por ejemplo, la moneda en $\ket{0}$ o $\ket{1}$) viven en un espacio de Hilbert.

---

##  2. Matriz hermítica: definición

Una matriz $A$ es **hermítica** si cumple:

$$
A^\dagger = A
$$

donde $A^\dagger$ es la conjugada transpuesta (trasponer la matriz y tomar conjugado complejo de cada entrada).

**Ejemplo:**

$$
A = \begin{bmatrix}
2 & -i \\
i & 3
\end{bmatrix},
\quad
A^\dagger =
\begin{bmatrix}
2 & -i \\
i & 3
\end{bmatrix}
= A
$$

---

##  3. Propiedades fundamentales

Las matrices hermíticas son cruciales porque:

- **Autovalores reales**  
  Si $A \ket{v} = \lambda \ket{v}$ con $\ket{v} \neq 0$, entonces $\lambda \in \mathbb{R}$.  
  > En física: los resultados de las mediciones deben ser **números reales**.

- **Autovectores ortogonales**  
  Los autovectores asociados a autovalores distintos cumplen:

  $$
  \braket{v_i | v_j} = 0 \quad \text{si } \lambda_i \neq \lambda_j
  $$

  > *Ortogonal* (como en geometría clásica: dos vectores perpendiculares).

- **Base ortonormal**  
  Si además los vectores están normalizados ($\|\ket{v}\|=1$), entonces forman una **base ortonormal**.  

  > *Ortonormal* = “perpendiculares” (orto) + “longitud uno” (normal).

- **Diagonalización unitaria**  
  Toda matriz hermítica puede escribirse como:

  $$
  A = U D U^\dagger
  $$

  donde $U$ es una matriz unitaria y $D$ es diagonal con los autovalores de $A$.  

  > Geométricamente: $U$ rota y refleja el espacio sin deformarlo.

---

##  4. Ejemplo en espacio de Hilbert cuántico (moneda cuántica)

Sea el observable **“medir cara o sello”**:

$$
Z =
\begin{bmatrix}
1 & 0 \\
0 & -1
\end{bmatrix}
$$

- $Z$ es hermítico porque $Z^\dagger = Z$.  
- Autovalores: $\{+1, -1\}$ → posibles resultados de la medición.  
- Autovectores:  

  $$
  \ket{0} = \begin{bmatrix}1 \\ 0\end{bmatrix}, 
  \quad
  \ket{1} = \begin{bmatrix}0 \\ 1\end{bmatrix}
  $$

En este espacio de Hilbert: $\{\ket{0}, \ket{1}\}$ es una **base ortonormal** (son perpendiculares y de norma 1).

---

##  5. Conexión con la medición

En cuántica, todo lo que se mide está representado por una **matriz hermítica**.

- Los **autovalores** son los resultados posibles de la medición.  
- Los **autovectores** son los estados hacia los cuales colapsa el sistema si se obtiene ese resultado.  

> Así, la **medición** es la traducción de una propiedad matemática (autovalores de una matriz hermítica) a un fenómeno físico (el resultado probabilístico real que observamos).


# Comparación de Estados Cuánticos (con forma tensorial)

| Tipo de estado      | Ejemplo en Dirac                                | Vector columna                          | Forma tensorial                          | Interpretación |
|---------------------|-------------------------------------------------|------------------------------------------|-------------------------------------------|----------------|
| **Puro**            | $\ket{\psi} = \ket{0}$                         | $\begin{bmatrix}1 \\ 0\end{bmatrix}$     | $\ket{0}$                                 | Estado definido sin incertidumbre (moneda fija en cara). |
| **Superposición**   | $\ket{\psi} = \tfrac{1}{\sqrt{2}}(\ket{0}+\ket{1})$ | $\tfrac{1}{\sqrt{2}}\begin{bmatrix}1 \\ 0\end{bmatrix}$ + $\tfrac{1}{\sqrt{2}}\begin{bmatrix}0 \\ 1\end{bmatrix}$ | ($\tfrac{1}{\sqrt{2}} \ket{0}+ \tfrac{1}{\sqrt{2}} \ket{1} )$ (un solo qubit) | Un qubit guarda amplitudes para $0$ y $1$ (moneda en el aire). |
| **Producto (2 qubits, separable)** | $\ket{\psi} = \ket{0}\otimes\tfrac{1}{\sqrt{2}}(\ket{0}+\ket{1})$ | $\tfrac{1}{\sqrt{2}}\begin{bmatrix}1 \\ 1 \\ 0 \\ 0\end{bmatrix}$ | Producto de estados individuales | Dos qubits independientes, no hay correlación al medir. |
| **Entrelazamiento** | $\ket{\psi} = \tfrac{1}{\sqrt{2}}(\ket{00}+\ket{11})$ | $\tfrac{1}{\sqrt{2}}\begin{bmatrix}1 \\ 0 \\ 0 \\ 1\end{bmatrix}$ | **No puede escribirse** como $\ket{a}\otimes\ket{b}$ | Dos qubits forman un sistema indivisible: medir uno fija el resultado del otro. |


# Marco Teórico: Procedimiento de Medición Cuántica

---

## Paso 1 — Estado inicial

Todo análisis de medición parte de un estado **normalizado**.  
Para un sistema general:

$$
\ket{\Psi}
$$

con 
$$
\braket{\Psi|\Psi} = 1.
$$

En el lenguaje matricial, un qubit es un vector en $\mathbb{C}^2$, y un sistema de $n$ qubits vive en $\mathbb{C}^{2^n}$.

Ejemplo (un qubit):

$$
\ket{\psi} = \sqrt{0.6}\ket{0} + \sqrt{0.4}\ket{1}
=
\begin{bmatrix}
\sqrt{0.6} \\
\sqrt{0.4}
\end{bmatrix}.
$$

---

## Paso 2 — Definir el observable / proyectores

La medición se define mediante un **observable hermítico** $M$ o mediante **proyectores $P_i$** que seleccionan subespacios asociados a cada resultado posible.

- Un observable $M$ admite una descomposición espectral:

$$
M = \sum_i \lambda_i P_i,
$$

donde $\lambda_i$ son los **autovalores** (resultados posibles de la medición) y $P_i$ son proyectores ortogonales sobre los autovectores correspondientes.

Cuando usamos proyectores en **notación matricial**, podemos entenderlos como **producto de un ket y un bra**:

###  Proyector de un qubit

En la base computacional $\{\ket{0}, \ket{1}\}$:

$$
\ket{0} = \begin{pmatrix}1\\0\end{pmatrix}, \quad
\ket{1} = \begin{pmatrix}0\\1\end{pmatrix}
$$

Proyectores:

$$
P_0 = \ket{0}\bra{0} = 
\begin{pmatrix}1\\0\end{pmatrix} 
\begin{pmatrix}1 & 0\end{pmatrix} 
= 
\begin{pmatrix}1 & 0\\0 & 0\end{pmatrix}
$$

$$
P_1 = \ket{1}\bra{1} = 
\begin{pmatrix}0\\1\end{pmatrix} 
\begin{pmatrix}0 & 1\end{pmatrix} 
= 
\begin{pmatrix}0 & 0\\0 & 1\end{pmatrix}
$$

- **Fila** = $\bra{0}$ o $\bra{1}$  
- **Columna** = $\ket{0}$ o $\ket{1}$  
- La fila “actúa” sobre el vector y la columna da la dirección proyectada.



###  Proyectores en 2 qubits (primer qubit)

Para medir solo el primer qubit:

$$
P_0 = \ket{0}\bra{0} \otimes I_2 = 
\begin{pmatrix}1 & 0\\0 & 0\end{pmatrix} \otimes 
\begin{pmatrix}1 & 0\\0 & 1\end{pmatrix} =
\begin{pmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{pmatrix}
$$

$$
P_1 = \ket{1}\bra{1} \otimes I_2 =
\begin{pmatrix}
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{pmatrix}
$$

- **Filas** corresponden al **bra del primer qubit**  
- **Columnas** corresponden al **ket del primer qubit**  
- El segundo qubit permanece intacto (tensor con $I$), por eso los proyectores seleccionan todos los estados donde el primer qubit es 0 o 1.

---

## Paso 3 — Calcular probabilidades

La probabilidad de obtener el resultado $i$ al medir es

$$
P(i) = \bra{\Psi}P_i\ket{\Psi}.
$$

Esto es equivalente a la norma cuadrada del vector proyectado:

$$
P(i) = \| P_i \ket{\Psi} \|^2.
$$

👉 **Ejemplo sencillo (un qubit):**

Si
$$
\ket{\psi}=\sqrt{0.6}\ket{0}+\sqrt{0.4}\ket{1},
$$

entonces:

$$
P(0) = |\sqrt{0.6}|^2 = 0.6,
\qquad
P(1) = |\sqrt{0.4}|^2 = 0.4.
$$

---
## Paso 4 — Estado posterior (colapso y normalización)

Una vez realizada la medición y obtenido el resultado $i$, el estado cuántico colapsa a:

$$
\ket{\Psi_i} = \frac{P_i \ket{\Psi}}{\sqrt{P(i)}}.
$$

### ¿Por qué normalizamos?
- $P_i \ket{\Psi}$ extrae la “parte” del estado que corresponde al resultado $i$.  
- Este vector, en general, **no está normalizado**.  
- Para que represente un nuevo estado físico válido, debemos dividirlo por su norma (es decir, por $\sqrt{P(i)}$).  

Esto garantiza que:
$$
\braket{\Psi_i|\Psi_i} = 1.
$$

---

### Ejemplo 1 (un qubit)

Sea:
$$
\ket{\psi} = \sqrt{0.6}\ket{0} + \sqrt{0.4}\ket{1}.
$$

Si medimos en la base computacional:

- **Resultado $0$**  
  $P(0) = 0.6$.  
  Vector proyectado:
  $$
  P_0 \ket{\psi} = \sqrt{0.6}\ket{0}.
  $$
  Estado normalizado:
  $$
  \ket{\psi_0} = \frac{\sqrt{0.6}\ket{0}}{\sqrt{0.6}} = \ket{0}.
  $$

- **Resultado $1$**  
  $P(1) = 0.4$.  
  Vector proyectado:
  $$
  P_1 \ket{\psi} = \sqrt{0.4}\ket{1}.
  $$
  Estado normalizado:
  $$
  \ket{\psi_1} = \frac{\sqrt{0.4}\ket{1}}{\sqrt{0.4}} = \ket{1}.
  $$

---

### Ejemplo 2 (dos qubits, medición parcial)

Estado:
$$
\ket{\Psi} = \sqrt{0.3}\ket{00} + \sqrt{0.3}\ket{01} + \sqrt{0.2}\ket{10} + \sqrt{0.2}\ket{11}.
$$

- **Medimos el primer qubit y obtenemos “0”**  
  Probabilidad:
  $$
  P(\text{1er}=0) = 0.3+0.3 = 0.6.
  $$
  Vector proyectado:
  $$
  P_0 \ket{\Psi} = \sqrt{0.3}\ket{00} + \sqrt{0.3}\ket{01}.
  $$
  Estado normalizado:
  $$
  \ket{\Psi'} = \frac{1}{\sqrt{0.6}} \left(\sqrt{0.3}\ket{00} + \sqrt{0.3}\ket{01}\right)
  = \frac{1}{\sqrt{2}}\left(\ket{00} + \ket{01}\right).
  $$

- **Medimos el primer qubit y obtenemos “1”**  
  Probabilidad:
  $$
  P(\text{1er}=1) = 0.2+0.2 = 0.4.
  $$
  Vector proyectado:
  $$
  P_1 \ket{\Psi} = \sqrt{0.2}\ket{10} + \sqrt{0.2}\ket{11}.
  $$
  Estado normalizado:
  $$
  \ket{\Psi''} = \frac{1}{\sqrt{0.4}} \left(\sqrt{0.2}\ket{10} + \sqrt{0.2}\ket{11}\right)
  = \frac{1}{\sqrt{2}} \left(\ket{10} + \ket{11}\right).
  $$

---

> **Idea clave**:  
> - La proyección selecciona la parte del estado compatible con el resultado.  
> - La normalización garantiza que el estado posterior siga siendo un **estado cuántico válido**.  
> - Después de la medición, el sistema ya **no está en superposición**: solo conserva la parte asociada al resultado observado.


# Ejercicio 1: Moneda cuántica **sin fases**

## 1) Estado inicial (definido “a mano”)

$$
\ket{\psi} \;=\; \sqrt{0.7}\,\ket{0} \;+\; \sqrt{0.3}\,\ket{1}.
$$

En **matricial** (base $\{\ket{0},\ket{1}\}$):

$$
\ket{\psi}
=
\begin{bmatrix}
\sqrt{0.7} \\
\sqrt{0.3}
\end{bmatrix}.
$$

---

## 2) ¿Qué se mide? (Proyectores)

- En **Dirac**:
  - $P_0 = \ket{0}\bra{0}$,
  - $P_1 = \ket{1}\bra{1}$.

- En **matrices**:

$$
P_0 =
\begin{bmatrix}
1 & 0\\
0 & 0
\end{bmatrix},
\qquad
P_1 =
\begin{bmatrix}
0 & 0\\
0 & 1
\end{bmatrix}.
$$

---

## 3) Probabilidades de medición

En Dirac:

- $P(0)=\bra{\psi}P_0\ket{\psi}=|\braket{0|\psi}|^2=0.7$  
- $P(1)=\bra{\psi}P_1\ket{\psi}=|\braket{1|\psi}|^2=0.3$

En matrices:

$$
P(0)=\bra{\psi}P_0\ket{\psi}=0.7,
\qquad
P(1)=\bra{\psi}P_1\ket{\psi}=0.3.
$$

✅ Chequeo: $0.7+0.3=1$.

---

## 4) Estado posterior a la medición (colapso)

### Si el resultado fue $0$:
- **No normalizado**: $P_0\ket{\psi} = \sqrt{0.7}\,\ket{0}$  
- **Normalizado**:

$$
\ket{\psi'}=\frac{P_0\ket{\psi}}{\sqrt{P(0)}}=\ket{0}.
$$

En matrices:

$$
P_0\ket{\psi}
=
\begin{bmatrix}1&0\\0&0\end{bmatrix}
\begin{bmatrix}\sqrt{0.7}\\ \sqrt{0.3}\end{bmatrix}
=
\begin{bmatrix}\sqrt{0.7}\\ 0\end{bmatrix}
\ \xrightarrow{\ \text{normaliza}\ }\ 
\begin{bmatrix}1\\ 0\end{bmatrix}.
$$

### Si el resultado fue $1$:
- **No normalizado**: $P_1\ket{\psi} = \sqrt{0.3}\,\ket{1}$  
- **Normalizado**:

$$
\ket{\psi'}=\frac{P_1\ket{\psi}}{\sqrt{P(1)}}=\ket{1}.
$$

En matrices:

$$
P_1\ket{\psi}
=
\begin{bmatrix}0&0\\0&1\end{bmatrix}
\begin{bmatrix}\sqrt{0.7}\\ \sqrt{0.3}\end{bmatrix}
=
\begin{bmatrix}0\\ \sqrt{0.3}\end{bmatrix}
\ \xrightarrow{\ \text{normaliza}\ }\ 
\begin{bmatrix}0\\ 1\end{bmatrix}.
$$



# Ejercicio  — Cálculo matricial paso a paso
**Dos “monedas” cuánticas independientes **

---

## 1) Vectores de estado (componentes)

Primer qubit:

$$
\ket{\psi} =
\begin{bmatrix}
\sqrt{0.6} \\
\sqrt{0.4}
\end{bmatrix}
$$

Segundo qubit:

$$
\ket{\phi} =
\begin{bmatrix}
\sqrt{0.5} \\
\sqrt{0.5}
\end{bmatrix}
$$

El producto tensorial $ \ket{\Psi} = \ket{\psi}\otimes\ket{\phi} $ se calcula componente a componente. Calculamos las cuatro componentes:

$$
\text{1ª componente:}\quad \sqrt{0.6}\cdot\sqrt{0.5}=\sqrt{0.3}
$$

$$
\text{2ª componente:}\quad \sqrt{0.6}\cdot\sqrt{0.5}=\sqrt{0.3}
$$

$$
\text{3ª componente:}\quad \sqrt{0.4}\cdot\sqrt{0.5}=\sqrt{0.2}
$$

$$
\text{4ª componente:}\quad \sqrt{0.4}\cdot\sqrt{0.5}=\sqrt{0.2}
$$

Por tanto, el estado conjunto en la base ordenada $\{\ket{00},\ket{01},\ket{10},\ket{11}\}$ es

$$
\ket{\Psi} =
\begin{bmatrix}
\sqrt{0.3} \\
\sqrt{0.3} \\
\sqrt{0.2} \\
\sqrt{0.2}
\end{bmatrix}
$$

---

## 2) Proyectores parciales sobre el primer qubit

Definimos los proyectores $P_0 = \ket{0}\bra{0}\otimes I$ y $P_1 = \ket{1}\bra{1}\otimes I$. En la base $\{\ket{00},\ket{01},\ket{10},\ket{11}\}$:

$$
P_0 =
\begin{bmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{bmatrix}
\qquad
P_1 =
\begin{bmatrix}
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{bmatrix}
$$

---

## 3) Acción de $P_0$ sobre $\ket{\Psi}$ (multiplicación matricial paso a paso)

Multiplicamos $P_0$ por $\ket{\Psi}$:

$$
P_0\ket{\Psi} =
\begin{bmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{bmatrix}
\begin{bmatrix}
\sqrt{0.3} \\ \sqrt{0.3} \\ \sqrt{0.2} \\ \sqrt{0.2}
\end{bmatrix}
=
\begin{bmatrix}
1\cdot\sqrt{0.3} + 0 + 0 + 0 \\
0 + 1\cdot\sqrt{0.3} + 0 + 0 \\
0 + 0 + 0\cdot\sqrt{0.2} + 0 \\
0 + 0 + 0 + 0\cdot\sqrt{0.2}
\end{bmatrix}
=
\begin{bmatrix}
\sqrt{0.3} \\ \sqrt{0.3} \\ 0 \\ 0
\end{bmatrix}
$$

Ese vector es el estado **no normalizado** tras la proyección.

---

## 4) Probabilidad de obtener “primer qubit = 0” (fórmula y cálculo explícito)

La probabilidad se obtiene como $P(\text{1er}=0)=\bra{\Psi}P_0\ket{\Psi}$. Escribimos primero la bra asociada a $\ket{\Psi}$:

$$
\bra{\Psi} =
\begin{bmatrix}
\sqrt{0.3} & \sqrt{0.3} & \sqrt{0.2} & \sqrt{0.2}
\end{bmatrix}
$$

Ahora calculamos:

$$
\bra{\Psi}P_0\ket{\Psi}
=
\begin{bmatrix}
\sqrt{0.3} & \sqrt{0.3} & \sqrt{0.2} & \sqrt{0.2}
\end{bmatrix}
\begin{bmatrix}
\sqrt{0.3} \\ \sqrt{0.3} \\ 0 \\ 0
\end{bmatrix}
$$

$$
=
\sqrt{0.3}\cdot\sqrt{0.3} + \sqrt{0.3}\cdot\sqrt{0.3} + \sqrt{0.2}\cdot 0 + \sqrt{0.2}\cdot 0
$$

$$
= 0.3 + 0.3 = 0.6
$$

Por tanto $P(\text{1er}=0)=0.6$.

---

## 5) Normalización del estado posterior (primer qubit = 0)

Tomamos el vector no normalizado $P_0\ket{\Psi} = \begin{bmatrix}\sqrt{0.3}\\ \sqrt{0.3}\\0\\0\end{bmatrix}$ y dividimos por $\sqrt{P(\text{1er}=0)} = \sqrt{0.6}$:

$$
\ket{\Psi'} = \frac{1}{\sqrt{0.6}} \begin{bmatrix}\sqrt{0.3}\\ \sqrt{0.3}\\0\\0\end{bmatrix}
$$

Calculando cada componente:

$$
\frac{\sqrt{0.3}}{\sqrt{0.6}} = \sqrt{\frac{0.3}{0.6}} = \sqrt{\frac{1}{2}} = \frac{1}{\sqrt{2}}
$$

Así:

$$
\ket{\Psi'} =
\frac{1}{\sqrt{2}}
\begin{bmatrix}
1 \\ 1 \\ 0 \\ 0
\end{bmatrix}
$$

Observación: éste vector se factoriza como

$$
\ket{\Psi'} = \ket{0}\otimes\frac{\ket{0}+\ket{1}}{\sqrt{2}}
$$

$$
\ket{\Psi''} =  \frac{1}{\sqrt{2}} \big( \ket{00} + \ket{01} \big)
$$
(es decir, primer qubit en $ \ket{0} $ y segundo en la superposición equilibrada).

---

## 6) Repetición del procedimiento para $P_1$ (primer qubit = 1)

Acción del proyector:

$$
P_1\ket{\Psi} =
\begin{bmatrix}
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
\sqrt{0.3} \\ \sqrt{0.3} \\ \sqrt{0.2} \\ \sqrt{0.2}
\end{bmatrix}
=
\begin{bmatrix}
0 \\ 0 \\ \sqrt{0.2} \\ \sqrt{0.2}
\end{bmatrix}
$$

Probabilidad:

$$
\bra{\Psi}P_1\ket{\Psi}
=
\begin{bmatrix}
\sqrt{0.3} & \sqrt{0.3} & \sqrt{0.2} & \sqrt{0.2}
\end{bmatrix}
\begin{bmatrix}
0 \\ 0 \\ \sqrt{0.2} \\ \sqrt{0.2}
\end{bmatrix}
=
0 + 0 + \sqrt{0.2}\cdot\sqrt{0.2} + \sqrt{0.2}\cdot\sqrt{0.2}
$$

$$
= 0.2 + 0.2 = 0.4
$$

Normalizamos dividiendo por $\sqrt{0.4}$:

$$
\ket{\Psi''} = \frac{1}{\sqrt{0.4}} \begin{bmatrix}0\\0\\\sqrt{0.2}\\\sqrt{0.2}\end{bmatrix}
=
\frac{1}{\sqrt{2}}
\begin{bmatrix}
0 \\ 0 \\ 1 \\ 1
\end{bmatrix}
=
\ket{1}\otimes\frac{\ket{0}+\ket{1}}{\sqrt{2}}
$$

$$

\ket{\Psi''} =  \frac{1}{\sqrt{2}} \big( \ket{10} + \ket{11} \big)

$$




---

## 7) Propiedades espectrales de $P_0$

- $P_0$ es hermítico e idempotente ($P_0^\dagger = P_0$, $P_0^2 = P_0$).
- Su espectro consiste en los valores $\{1,1,0,0\}$ (es decir, autovalores 1 y 0).
- Los autovectores correspondientes son la base estándar:
  
  $$\text{autovalor }1:\quad \ket{00}=\begin{bmatrix}1\\0\\0\\0\end{bmatrix},\quad \ket{01}=\begin{bmatrix}0\\1\\0\\0\end{bmatrix}$$ 

  $$\text{autovalor }0:\quad \ket{10}=\begin{bmatrix}0\\0\\1\\0\end{bmatrix},\quad \ket{11}=\begin{bmatrix}0\\0\\0\\1\end{bmatrix}$$

Se puede escribir la descomposición espectral como

$$
P_0 = \ket{00}\bra{00} + \ket{01}\bra{01}
$$

---

## 8) Conclusión

- Medir el primer qubit equivale a aplicar el proyector $P_0$ o $P_1$; la probabilidad es $P(i)=\bra{\Psi}P_i\ket{\Psi}$ y el estado posterior es $\dfrac{P_i\ket{\Psi}}{\sqrt{\bra{\Psi}P_i\ket{\Psi}}}$.  
- En este ejemplo $P(\text{1er}=0)=0.6$, $P(\text{1er}=1)=0.4$, y los estados colapsados son $\ket{0}\otimes\frac{\ket{0}+\ket{1}}{\sqrt{2}}$ y $\ket{1}\otimes\frac{\ket{0}+\ket{1}}{\sqrt{2}}$ respectivamente.

---


# Medición de dos qubits independientes: paso a paso en notación de Dirac

## 1 Estado inicial

Sistema de dos qubits independientes:

$$
\ket{\Psi} = (\color{blue}{\sqrt{0.6}}\ket{0} + \color{green}{\sqrt{0.4}}\ket{1}) \color{black}\otimes \color{black}(\sqrt{0.5}\ket{0} + \sqrt{0.5}\ket{1})
$$
$$
\ket{\Psi} = (\color{blue}{\sqrt{0.6}}\ket{0} + \color{green} {\sqrt{0.4}}\ket{1}) \otimes \color{black} \frac{1}{\sqrt{2}}(\ket{0}+\ket{1})
$$

Si lo expandimos:
$$
\ket{\Psi} = \color{blue}{\frac{\sqrt{0.6}}{\sqrt{2}}} (\ket{00}+\ket{01}) + \color{green}{\frac{\sqrt{0.4}}{\sqrt{2}}} (\ket{10}+\ket{11})
$$

$$
\ket{\Psi} = \frac{\sqrt{0.6}}{\sqrt{2}} (\ket{00}+\ket{01}) + \frac{\sqrt{0.4}}{\sqrt{2}} (\ket{10}+\ket{11})
$$

- **Nota:** azul → primer qubit = 0, verde → primer qubit = 1  
- Segundo qubit está claramente en superposición $\sqrt{0.5}\ket{0} + \sqrt{0.5}\ket{1}$

> ### Explicación del factor $\frac{1}{\sqrt{2}}$ en el segundo qubit
>
>El segundo qubit está en superposición equitativa:
>
>$$
>\ket{\phi} = \alpha \ket{0} + \beta \ket{1}
>$$
>
>Para que $\ket{\phi}$ sea un **estado cuántico válido**, debe cumplir la **normalización**:
>
>$$
>|\alpha|^2 + |\beta|^2 = 1
>$$
>
>Si queremos que $\ket{0}$ y $\ket{1}$ tengan la **misma amplitud**, entonces:
>
>$$
>|\alpha|^2 = |\beta|^2 \implies 2|\alpha|^2 = 1 \implies |\alpha| = \frac{1}{\sqrt{2}}
>$$
>
>Por lo tanto, la superposición equitativa es:
>
>$$
>\ket{\phi} = \frac{1}{\sqrt{2}} \ket{0} + \frac{1}{\sqrt{2}} \ket{1}
>$$
>
> Esto explica el origen del $\frac{1}{\sqrt{2}}$ en el segundo qubit.  
> Cuando combinamos con el primer qubit, cada estado conjunto $\ket{00}, \ket{01}, \ket{10}, \ket{11}$ hereda este factor en su amplitud.

---

## 2️ Medición del primer qubit

Proyectores:


>- <span style="color:blue">P₀:</span> selecciona estados donde primer qubit = 0  
>$$
>P_0 = \ket{0}\bra{0} \otimes I, 
>$$

>- <span style="color:green">P₁:</span> selecciona estados donde primer qubit = 1  
>$$
>P_1 = \ket{1}\bra{1} \otimes I
>$$
---

## 3️ Probabilidades de los resultados

**Primer qubit = 0:**  
- Estados: $\ket{00}$ y $\ket{01}$, amplitud $\color{blue}{\sqrt{0.6} \cdot \sqrt{0.5}} = \sqrt{0.3}$  
- Probabilidad:

$$
P(\text{1er}=0) = |\sqrt{0.3}|^2 + |\sqrt{0.3}|^2 = 0.3 + 0.3 = 0.6
$$

**Primer qubit = 1:**  
- Estados: $\ket{10}$ y $\ket{11}$, amplitud $\color{green}{\sqrt{0.4} \cdot \sqrt{0.5}} = \sqrt{0.2}$  
- Probabilidad:

$$
P(\text{1er}=1) = |\sqrt{0.2}|^2 + |\sqrt{0.2}|^2 = 0.2 + 0.2 = 0.4
$$

---

## 4️ Estado colapsado

**Si primer qubit = 0 (P = 0.6):**

$$
\ket{\Psi_0} = \frac{1}{\sqrt{0.6}} \cdot \sqrt{0.3} (\ket{00}+\ket{01}) = \frac{1}{\sqrt{2}} (\ket{00}+\ket{01})
$$

**Si primer qubit = 1 (P = 0.4):**

$$
\ket{\Psi_1} = \frac{1}{\sqrt{0.4}} \cdot \sqrt{0.2} (\ket{10}+\ket{11}) = \frac{1}{\sqrt{2}} (\ket{10}+\ket{11})
$$

- Segundo qubit permanece en superposición $\sqrt{0.5}\ket{0} + \sqrt{0.5}\ket{1}$ en ambas ramas

---

## 5️ Interpretación final

- <span style="color:blue">Primer qubit = 0 (60% de probabilidad)</span> → segundo qubit: $\sqrt{0.5}\ket{00} + \sqrt{0.5}\ket{01}$  
- <span style="color:green">Primer qubit = 1 (40% de probabilidad)</span> → segundo qubit: $\sqrt{0.5}\ket{10} + \sqrt{0.5}\ket{11}$  

> **Observación:** el segundo qubit **no colapsa a un valor fijo**, porque ambos qubits son independientes.



In [2]:
import numpy as np

# --- 1) Definición de los estados individuales ---
psi = np.array([np.sqrt(0.6), np.sqrt(0.4)])   # |ψ>
phi = np.array([np.sqrt(0.5), np.sqrt(0.5)])   # |φ>

# --- 2) Producto tensorial ---
Psi = np.kron(psi, phi)   # estado conjunto |Ψ>
print("Estado conjunto |Ψ>:\n", Psi)

# --- 3) Proyectores parciales ---
P0 = np.diag([1,1,0,0])   # |0><0| ⊗ I
P1 = np.diag([0,0,1,1])   # |1><1| ⊗ I

# --- 4) Acción de P0 ---
proj0 = P0 @ Psi
prob0 = np.vdot(Psi, proj0)   # <Ψ|P0|Ψ>
Psi0 = proj0 / np.sqrt(prob0) if prob0 > 0 else None

print("\nProbabilidad primer qubit=0:", prob0)
print("Estado normalizado si primer=0:\n", Psi0)

# --- 5) Acción de P1 ---
proj1 = P1 @ Psi
prob1 = np.vdot(Psi, proj1)   # <Ψ|P1|Ψ>
Psi1 = proj1 / np.sqrt(prob1) if prob1 > 0 else None

print("\nProbabilidad primer qubit=1:", prob1)
print("Estado normalizado si primer=1:\n", Psi1)

# --- 6) Autovalores y autovectores de P0 ---
eigvals, eigvecs = np.linalg.eig(P0)
print("\nAutovalores de P0:\n", eigvals)
print("Autovectores de P0 (columnas):\n", eigvecs)

# --- 7) Autovalores y autovectores de P1 ---
eigvals, eigvecs = np.linalg.eig(P1)
print("\nAutovalores de P1:\n", eigvals)
print("Autovectores de P1 (columnas):\n", eigvecs)



Estado conjunto |Ψ>:
 [0.54772256 0.54772256 0.4472136  0.4472136 ]

Probabilidad primer qubit=0: 0.6000000000000002
Estado normalizado si primer=0:
 [0.70710678 0.70710678 0.         0.        ]

Probabilidad primer qubit=1: 0.4000000000000001
Estado normalizado si primer=1:
 [0.         0.         0.70710678 0.70710678]

Autovalores de P0:
 [1. 1. 0. 0.]
Autovectores de P0 (columnas):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Autovalores de P1:
 [0. 0. 1. 1.]
Autovectores de P1 (columnas):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
